export const TIMEOUT_ERROR = 'TIMEOUT_ERROR'
export const NETWORK_ERROR = 'NETWORK_ERROR'
export const GEO_LOCATION_TIMEOUT = 1000 * 10 // 10 seconds
export const GEO_LOCATION_MAXIMUMAGE = 1000 * 60 * 5 // 5 minutes

export const STATUS_DRAFT = 'DRAFT'
export const STATUS_PENDING = 'PENDING'
export const STATUS_ACTIVE = 'ACTIVE'
export const STATUS_INACTIVE = 'INACTIVE'
export const STATUS_EXPIRED = 'EXPIRED'
export const STATUS_SOLD = 'SOLD'
export const STATUS_REJECTED = 'REJECTED'
export const STATUS_DELETED = 'DELETED'

export const STOCK_TYPE_CURRENT = 'current'
export const STOCK_TYPE_UPCOMING = 'upcoming'
export const STOCK_TYPE_SOLD = 'sold'

export const SORT_BY_FEATURED = 'featured'
export const SORT_BY_LATEST = 'latest'
export const SORT_BY_RELEVANCE = 'relevance'
export const SORT_BY_LOWEST_PRICE = 'lowestPrice'
export const SORT_BY_HIGHEST_PRICE = 'relevance'
export const SORT_BY_OLDEST_VEHICLES = 'oldestVehicles'
export const SORT_BY_NEWEST_VEHICLES = 'newestVehicles'
export const SORT_BY_LOWEST_MILEAGE = 'lowestMileage'
export const SORT_BY_HIGHEST_MILEAGE = 'highestMileage'

export const MATCH_ALL_QUERY = {"match_all": {}}

export const LABLE_EXCLUSIVE = 'exclusive'
export const LABLE_AWESOME = 'awesome'
export const LABLE_FEATURED = 'featured'
export const LABLE_SPECIAL_SALE = 'special'
export const LABEL_UPCOMING = 'upcoming'
export const LABEL_BASIC = 'basic'

export const MIN_SCORE_EXCLUSIVE = 170
export const MIN_SCORE_AWESOME = 150
export const MIN_SCORE_FEATURED = 70
export const MIN_SCORE_SPECIAL_SALE = 999

export const NOTI_SP_CAR = 'NOTI_SP_CAR'
export const NOTI_SP_COUPON = 'NOTI_SP_COUPON'
export const NOTI_EVT_SIGNUP = 'NOTI_EVT_SIGNUP'

export const FB_EVENT = {
    AD_CLICK_FROM_LISTINGS: 'AD_CLICK_FROM_LISTINGS',
    AD_CLICK_FROM_LISTING_DETAIL: 'AD_CLICK_FROM_LISTING_DETAIL',
    AD_CLICK_FROM_SHOWROOM_LISTING_DETAIL: 'AD_CLICK_FROM_SHOWROOM_LISTING_DETAIL',
    AD_CLICK_FROM_COUPONS: 'AD_CLICK_FROM_COUPONS',
    AD_CLICK_FROM_COUPON_DETAIL: 'AD_CLICK_FROM_COUPON_DETAIL',

    DEALER_EMAIL_CLICK: 'DEALER_EMAIL_CLICK',
    DEALER_PHONE_CALL: 'DEALER_PHONE_CALL',
    DEALER_GET_DIRECTION: 'DEALER_GET_DIRECTION',
    DEALER_SHOWROOM_FROM_LISTING: 'DEALER_SHOWROOM_FROM_LISTING',
    DEALER_SHOWROOM_EMAIL_CLICK: 'DEALER_SHOWROOM_EMAIL_CLICK',

    WORKSHOP_EMAIL_CLICK: 'WORKSHOP_EMAIL_CLICK',
    WORKSHOP_PHONE_CALL: 'WORKSHOP_PHONE_CALL',
    WORKSHOP_GET_DIRECTION: 'WORKSHOP_GET_DIRECTION',
    WORKSHOP_SHOWROOM_FROM_LISTING: 'WORKSHOP_SHOWROOM_FROM_LISTING',
    WORKSHOP_SHOWROOM_EMAIL_CLICK: 'WORKSHOP_SHOWROOM_EMAIL_CLICK',

    SHOWROOM_LISTING_DETAIL: 'SHOWROOM_LISTING_DETAIL',

    LISTING_DETAIL: 'LISTING_DETAIL',
    LISTING_DETAIL_TAB_CHANGE: 'LISTING_DETAIL_TAB_CHANGE',
    LISTING_SAVE_LOGIN: 'LISTING_SAVE_LOGIN',
    LISTING_QUICK_SEARCH: 'LISTING_QUICK_SEARCH',
    LISTING_REFINE_SERACH: 'LISTING_REFINE_SERACH',
    LISTING_SORTBY: 'LISTING_SORTBY',
    LISTING_REGION: 'LISTING_REGION',
    LISTING_VIEW_TYPE_CHANGE: 'LISTING_VIEW_TYPE_CHANGE',

    COUPON_DETAIL: 'COUPON_DETAIL',
    COUPON_SAVE_LOGIN: 'COUPON_SAVE_LOGIN',
    COUPON_QUICK_SEARCH: 'COUPON_QUICK_SEARCH',
    COUPON_CATEGORY_SEARCH: 'COUPON_CATEGORY_SEARCH',
    COUPON_SORTBY: 'COUPON_SORTBY',
    COUPON_REGION: 'COUPON_REGION',
    COUPON_LOGIN_FOR_REVIEW: 'COUPON_LOGIN_FOR_REVIEW',
    COUPON_LOGIN_FOR_SAVE: 'COUPON_LOGIN_FOR_SAVE',
    COUPON_WRITE_REVIEW: 'COUPON_WRITE_REVIEW',
    
    OPEN_SELL_MY_CAR_PAGE: 'OPEN_SELL_MY_CAR_PAGE',
    OPEN_SELL_MY_CAR_WEB: 'OPEN_SELL_MY_CAR_WEB',
    
    TAP_TO_LISTING: 'TAP_TO_LISTING',
    TAP_TO_COUPON: 'TAP_TO_COUPON',
    
    TOGGLE_TO_LISTING: 'TOGGLE_TO_LISTING',
    TOGGLE_TO_COUPON: 'TOGGLE_TO_COUPON',

    SHARE_CAR: 'SHARE_CAR',
    SHARE_COUPON: 'SHARE_COUPON',

    USER_SAVE_LISTING: 'USER_SAVE_LISTING',
    USER_SAVE_COUPON: 'USER_SAVE_COUPON',

    USER_FB_SIGNUP: 'USER_FB_SIGNUP',
    USER_GOOGLE_SIGNUP: 'USER_GOOGLE_SIGNUP',
    
    USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
    USER_SIGNUP_FAILED: 'USER_SIGNUP_FAILED',
    USER_SIGNUP_ERROR: 'USER_SIGNUP_ERROR',

    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
    USER_LOGIN_ERROR: 'USER_LOGIN_ERROR',

    USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
    USER_LOGOUT_FAILED: 'USER_LOGOUT_FAILED',
    USER_LOGOUT_ERROR: 'USER_LOGOUT_ERROR',

    USER_FB_LOGIN_SUCCESS: 'USER_FB_LOGIN_SUCCESS',
    USER_FB_LOGIN_FAILED: 'USER_FB_LOGIN_FAILED',
    USER_FB_LOGIN_ERROR: 'USER_FB_LOGIN_ERROR',

    USER_GOOGLE_LOGIN_SUCCESS: 'USER_GOOGLE_LOGIN_SUCCESS',
    USER_GOOGLE_LOGIN_FAILED: 'USER_GOOGLE_LOGIN_FAILED',
    USER_GOOGLE_LOGIN_ERROR: 'USER_GOOGLE_LOGIN_ERROR',
    
    VIEW_MY_INFO: 'VIEW_MY_INFO'
}