project 'CarMateApp.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CarMateApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  react_native_path = "../node_modules/react-native"

  # Pods for CarMate
  pod 'Firebase/Core', '~> 5.0.1'
  pod 'Firebase/AdMob'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  #pod 'Firebase/Crash'
  pod 'Firebase/Database'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Messaging'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Storage'
  pod 'GoogleSignIn'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod "yoga", :path => "#{react_native_path}/ReactCommon/yoga"
  pod "React", :path => react_native_path, :subspecs => [
    'Core',
    'DevSupport', 
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
end
   
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
#target 'CarMate staging' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CarMate staging
  #pod 'Firebase/Core'

  #pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

# [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
#pod 'Firebase/AdMob'
#pod 'Firebase/Auth'
#pod 'Firebase/Crash'
#pod 'Firebase/Database'
#pod 'Firebase/DynamicLinks'
#pod 'Firebase/Messaging'
#pod 'Firebase/RemoteConfig'
#pod 'Firebase/Storage'

#pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
#pod 'React', :path => '../node_modules/react-native', :subspecs => [
  #'Core',
  # Add any other subspecs you want to use in your project
#]

# Temporary workaround for https://github.com/invertase/react-native-firebase/issues/395
#post_install do
  #`rm -rf Pods/leveldb-library/port/win`
#end

#end
